[package]
name = "c3p0_pg"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
postgres = { version = "0.15", features = ["with-serde_json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
lazy_static = "1.3"
r2d2 = "0.8"
r2d2_postgres = "0.14"
testcontainers = "0.6"
