[package]
name = "c3p0_pg"
license = "MIT"
version = "0.2.3"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["postgres", "pg", "json"]

[dependencies]
c3p0 = { path = "../c3p0", version = "0.2.3" }
log = "0.4"
postgres = { version = "0.15", features = ["with-serde_json"] }
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
lazy_static = "1.3"
maybe-single = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.14"
serde_derive = "1.0"
testcontainers = "0.6"
