[package]
name = "c3p0_pg"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"

[dependencies]
log = "0.4"
c3p0 = { path = "../c3p0", version = "0.2.0" }
postgres = { version = "0.15", features = ["with-serde_json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
testcontainers = "0.5"
